# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

model_mlik_ratio <- function(y, Xgbg, g, q_o, Xgbg_a, g_a, q_a) {
    .Call(`_bmms_model_mlik_ratio`, y, Xgbg, g, q_o, Xgbg_a, g_a, q_a)
}

VSModule_export <- function(s, y, X, MCMC, g, sprior, fixsigma = FALSE, binary = FALSE) {
    .Call(`_bmms_VSModule_export`, s, y, X, MCMC, g, sprior, fixsigma, binary)
}

ModularVS_export <- function(y, Xall, starting, MCMC, gg, ss, binary = FALSE) {
    .Call(`_bmms_ModularVS_export`, y, Xall, starting, MCMC, gg, ss, binary)
}

X2Dgrid <- function(x1, x2) {
    .Call(`_bmms_X2Dgrid`, x1, x2)
}

rndpp_bern <- function(p) {
    .Call(`_bmms_rndpp_bern`, p)
}

split_struct_ratio <- function(prop_split, orig_split, p, param) {
    .Call(`_bmms_split_struct_ratio`, prop_split, orig_split, p, param)
}

bmms_setdiff <- function(x, y) {
    .Call(`_bmms_bmms_setdiff`, x, y)
}

rndpp_unif_int <- function(max) {
    .Call(`_bmms_rndpp_unif_int`, max)
}

rndpp_discrete <- function(probs) {
    .Call(`_bmms_rndpp_discrete`, probs)
}

rndpp_gamma <- function(alpha, beta) {
    .Call(`_bmms_rndpp_gamma`, alpha, beta)
}

rndpp_normal <- function(mean, sigma) {
    .Call(`_bmms_rndpp_normal`, mean, sigma)
}

rndpp_mvnormal <- function(n, mean, sigma) {
    .Call(`_bmms_rndpp_mvnormal`, n, mean, sigma)
}

col_eq_check <- function(A) {
    .Call(`_bmms_col_eq_check`, A)
}

col_sums <- function(matty) {
    .Call(`_bmms_col_sums`, matty)
}

single_split <- function(Jcoarse, where, p) {
    .Call(`_bmms_single_split`, Jcoarse, where, p)
}

multi_split <- function(Jcoarse, where, p) {
    .Call(`_bmms_multi_split`, Jcoarse, where, p)
}

exclude <- function(test, excl) {
    .Call(`_bmms_exclude`, test, excl)
}

splitsub_to_splitmask <- function(splits, p1, p2) {
    .Call(`_bmms_splitsub_to_splitmask`, splits, p1, p2)
}

splitmask_to_splitsub <- function(splitmask) {
    .Call(`_bmms_splitmask_to_splitsub`, splitmask)
}

row_intersection <- function(mat1, mat2) {
    .Call(`_bmms_row_intersection`, mat1, mat2)
}

row_difference <- function(mat1, mat2) {
    .Call(`_bmms_row_difference`, mat1, mat2)
}

splits_augmentation <- function(splits) {
    .Call(`_bmms_splits_augmentation`, splits)
}

splitsub_to_groupmask <- function(splits, p1, p2) {
    .Call(`_bmms_splitsub_to_groupmask`, splits, p1, p2)
}

mat_unique <- function(A) {
    .Call(`_bmms_mat_unique`, A)
}

mask_oneval <- function(A, mask, val) {
    .Call(`_bmms_mask_oneval`, A, mask, val)
}

mask_oneval_sum <- function(A, mask, val) {
    .Call(`_bmms_mask_oneval_sum`, A, mask, val)
}

mask_cube_slice <- function(C, slice, mask, val) {
    .Call(`_bmms_mask_cube_slice`, C, slice, mask, val)
}

mat_to_vec_by_region <- function(A, mask, unique_regions) {
    .Call(`_bmms_mat_to_vec_by_region`, A, mask, unique_regions)
}

cube_to_mat_by_region <- function(C, mask, unique_regions) {
    .Call(`_bmms_cube_to_mat_by_region`, C, mask, unique_regions)
}

unmask_vector <- function(beta, regions, mask) {
    .Call(`_bmms_unmask_vector`, beta, regions, mask)
}

load_splits <- function(maxlevs) {
    .Call(`_bmms_load_splits`, maxlevs)
}

merge_splits <- function(old_splits, new_splits) {
    .Call(`_bmms_merge_splits`, old_splits, new_splits)
}

cube_mean <- function(X, dim) {
    .Call(`_bmms_cube_mean`, X, dim)
}

cube_sum <- function(X, dim) {
    .Call(`_bmms_cube_sum`, X, dim)
}

splitmask_focus <- function(mask_of_splits, onesplit, radius_int = 1L) {
    .Call(`_bmms_splitmask_focus`, mask_of_splits, onesplit, radius_int)
}

number_availables <- function(splitmask_focus) {
    .Call(`_bmms_number_availables`, splitmask_focus)
}

split_move2d <- function(mask_of_splits, mask_nosplits, onesplit, to_from_ratio, radius_int = 1L) {
    .Call(`_bmms_split_move2d`, mask_of_splits, mask_nosplits, onesplit, to_from_ratio, radius_int)
}

index_to_subscript <- function(index, m) {
    .Call(`_bmms_index_to_subscript`, index, m)
}

split_add2d <- function(mask_of_splits, mask_nosplits, lev, to_from_ratio) {
    .Call(`_bmms_split_add2d`, mask_of_splits, mask_nosplits, lev, to_from_ratio)
}

split_drop2d <- function(mask_of_splits, mask_nosplits, lev, to_from_ratio) {
    .Call(`_bmms_split_drop2d`, mask_of_splits, mask_nosplits, lev, to_from_ratio)
}

stage_drop2d <- function(mask_of_splits, mask_nosplits, lev, to_from_ratio) {
    invisible(.Call(`_bmms_stage_drop2d`, mask_of_splits, mask_nosplits, lev, to_from_ratio))
}

proposal_move <- function(current_split_mask, mask_nosplits, current_splits, which_lev, which_split, radius) {
    .Call(`_bmms_proposal_move`, current_split_mask, mask_nosplits, current_splits, which_lev, which_split, radius)
}

bmms_soi <- function(y, X, splits, mask_forbid, lambda_splits, lambda_ridge, mcmc, burn, radius, max_stages, start_movinglev, partnum, save = TRUE, save_splitmask = TRUE) {
    .Call(`_bmms_bmms_soi`, y, X, splits, mask_forbid, lambda_splits, lambda_ridge, mcmc, burn, radius, max_stages, start_movinglev, partnum, save, save_splitmask)
}

bmms_soi_binary <- function(y, X, splits, mask_forbid, lambda_splits, lambda_ridge, mcmc, burn, radius, max_stages, start_movinglev, partnum, save = TRUE, save_splitmask = TRUE, fixsigma = TRUE) {
    .Call(`_bmms_bmms_soi_binary`, y, X, splits, mask_forbid, lambda_splits, lambda_ridge, mcmc, burn, radius, max_stages, start_movinglev, partnum, save, save_splitmask, fixsigma)
}

rndpp_stdmvnormal <- function(n, dimension) {
    .Call(`_bmms_rndpp_stdmvnormal`, n, dimension)
}

rndpp_mvt <- function(n, mu, sigma, df) {
    .Call(`_bmms_rndpp_mvt`, n, mu, sigma, df)
}

my_bayeslm <- function(y, X, fixs) {
    .Call(`_bmms_my_bayeslm`, y, X, fixs)
}

lambda_prior_mhr <- function(lambda_now, lambda_prop) {
    .Call(`_bmms_lambda_prior_mhr`, lambda_now, lambda_prop)
}

lambda_lik_mhr <- function(lambda, lambda_prop, p, mfact) {
    .Call(`_bmms_lambda_lik_mhr`, lambda, lambda_prop, p, mfact)
}

lreg_lik_mhr <- function(y, x, b_prop, b, sigmasq_prop, sigmasq) {
    .Call(`_bmms_lreg_lik_mhr`, y, x, b_prop, b, sigmasq_prop, sigmasq)
}

bayes_ridge <- function(y, X, mcmc = 1000L, burn = 0L) {
    .Call(`_bmms_bayes_ridge`, y, X, mcmc, burn)
}

hat_alt <- function(X) {
    .Call(`_bmms_hat_alt`, X)
}

hat <- function(X) {
    .Call(`_bmms_hat`, X)
}

m0mvnorm_dens <- function(x, Si) {
    .Call(`_bmms_m0mvnorm_dens`, x, Si)
}

clm_marglik <- function(y, Mi, Si, muSimu, a, b) {
    .Call(`_bmms_clm_marglik`, y, Mi, Si, muSimu, a, b)
}

m0mvnorm_dens_gratio <- function(yy, yPxy, g, p) {
    .Call(`_bmms_m0mvnorm_dens_gratio`, yy, yPxy, g, p)
}

clm_marglik_gratio <- function(yy, yPxy, g, n, p, a, b) {
    .Call(`_bmms_clm_marglik_gratio`, yy, yPxy, g, n, p, a, b)
}

lm_gprior <- function(y, X, g = -1.0, fixs = FALSE) {
    .Call(`_bmms_lm_gprior`, y, X, g, fixs)
}

boolbern <- function(p) {
    .Call(`_bmms_boolbern`, p)
}

bvs <- function(y, X, prior, mcmc, g = -1.0, model_prior_par = 1.0, fixs = FALSE) {
    .Call(`_bmms_bvs`, y, X, prior, mcmc, g, model_prior_par, fixs)
}

rndpp_sample1_comp <- function(x, p, current_split, decay = 4.0) {
    .Call(`_bmms_rndpp_sample1_comp`, x, p, current_split, decay)
}

rndpp_shuffle <- function(x) {
    .Call(`_bmms_rndpp_shuffle`, x)
}

sample_index <- function(n, vsize) {
    .Call(`_bmms_sample_index`, n, vsize)
}

sample_one_int <- function(vsize) {
    .Call(`_bmms_sample_one_int`, vsize)
}

reshaper <- function(J_field, s) {
    .Call(`_bmms_reshaper`, J_field, s)
}

totsplit_prior_ratio <- function(tot_split_prop, tot_split_orig, norp, ss, lambda_prop) {
    .Call(`_bmms_totsplit_prior_ratio`, tot_split_prop, tot_split_orig, norp, ss, lambda_prop)
}

splitpar_prior <- function(x, tot_split, norp, ss) {
    .Call(`_bmms_splitpar_prior`, x, tot_split, norp, ss)
}

totstage_prior_ratio <- function(tot_stage_prop, tot_stage_orig, norp, curr_n_splits, direction) {
    .Call(`_bmms_totstage_prior_ratio`, tot_stage_prop, tot_stage_orig, norp, curr_n_splits, direction)
}

splits_truncate <- function(splits, k) {
    .Call(`_bmms_splits_truncate`, splits, k)
}

bmms_learn <- function(y, X, max_stages, lambda = 10.0, mcmc = 100L, burn = 50L, silent = TRUE) {
    .Call(`_bmms_bmms_learn`, y, X, max_stages, lambda, mcmc, burn, silent)
}

bmms_learn_fixk <- function(y, X, start_splits, lambda = 10.0, ii = 0L, ll = 0L, mcmc = 100L, burn = 50L, silent = TRUE) {
    .Call(`_bmms_bmms_learn_fixk`, y, X, start_splits, lambda, ii, ll, mcmc, burn, silent)
}

bmms_moveonly <- function(y, X, start_splits, ii = 0L, ll = 0L, mcmc = 100L, burn = 50L, silent = TRUE) {
    .Call(`_bmms_bmms_moveonly`, y, X, start_splits, ii, ll, mcmc, burn, silent)
}

bMMs <- function(y, X, g, mcmc, burn, splits, silent = TRUE) {
    .Call(`_bmms_bMMs`, y, X, g, mcmc, burn, splits, silent)
}

pnorm01_vec <- function(x, lower = 1L, logged = 0L) {
    .Call(`_bmms_pnorm01_vec`, x, lower, logged)
}

qnorm01_vec <- function(x, lower = 1L, logged = 0L) {
    .Call(`_bmms_qnorm01_vec`, x, lower, logged)
}

log1p_vec <- function(x) {
    .Call(`_bmms_log1p_vec`, x)
}

usetdiff <- function(x, y) {
    .Call(`_bmms_usetdiff`, x, y)
}

lnNpr_cpp <- function(a, b) {
    .Call(`_bmms_lnNpr_cpp`, a, b)
}

cholperm_cpp <- function(Sig, l, u) {
    .Call(`_bmms_cholperm_cpp`, Sig, l, u)
}

gradpsi_cpp <- function(y, L, l, u, grad) {
    .Call(`_bmms_gradpsi_cpp`, y, L, l, u, grad)
}

armasolve <- function(A, grad) {
    .Call(`_bmms_armasolve`, A, grad)
}

nleq <- function(l, u, L) {
    .Call(`_bmms_nleq`, l, u, L)
}

ntail_cpp <- function(l, u) {
    .Call(`_bmms_ntail_cpp`, l, u)
}

trnd_cpp <- function(l, u) {
    .Call(`_bmms_trnd_cpp`, l, u)
}

tn_cpp <- function(l, u) {
    .Call(`_bmms_tn_cpp`, l, u)
}

trandn_cpp <- function(l, u) {
    .Call(`_bmms_trandn_cpp`, l, u)
}

mvnrnd_cpp <- function(n, L, l, u, mu, logpr) {
    .Call(`_bmms_mvnrnd_cpp`, n, L, l, u, mu, logpr)
}

psy_cpp <- function(x, L, l, u, mu) {
    .Call(`_bmms_psy_cpp`, x, L, l, u, mu)
}

mvrandn_cpp <- function(l_in, u_in, Sig, n) {
    .Call(`_bmms_mvrandn_cpp`, l_in, u_in, Sig, n)
}

mvtruncnormal <- function(mean, l_in, u_in, Sig, n) {
    .Call(`_bmms_mvtruncnormal`, mean, l_in, u_in, Sig, n)
}

mvtruncnormal_eye1 <- function(mean, l_in, u_in) {
    .Call(`_bmms_mvtruncnormal_eye1`, mean, l_in, u_in)
}

rndpp_mvnormal2 <- function(n, mu, sigma) {
    .Call(`_bmms_rndpp_mvnormal2`, n, mu, sigma)
}

rndpp_mvnormalnew <- function(n, mean, sigma) {
    .Call(`_bmms_rndpp_mvnormalnew`, n, mean, sigma)
}

get_S <- function(y, X) {
    .Call(`_bmms_get_S`, y, X)
}

get_Ddiag <- function(Sigma, S) {
    .Call(`_bmms_get_Ddiag`, Sigma, S)
}

diag_default_mult <- function(A, D) {
    .Call(`_bmms_diag_default_mult`, A, D)
}

diag_custom_mult <- function(A, D) {
    .Call(`_bmms_diag_custom_mult`, A, D)
}

beta_post_sample <- function(mu, Sigma, S, Ddiag, sample_size = 1L) {
    .Call(`_bmms_beta_post_sample`, mu, Sigma, S, Ddiag, sample_size)
}

