# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_splits <- function(maxlevs, sname) {
    .Call('_bmms_load_splits', PACKAGE = 'bmms', maxlevs, sname)
}

cube_mean <- function(X, dim) {
    .Call('_bmms_cube_mean', PACKAGE = 'bmms', X, dim)
}

cube_sum <- function(X, dim) {
    .Call('_bmms_cube_sum', PACKAGE = 'bmms', X, dim)
}

number_availables <- function(splitmask_focus) {
    .Call('_bmms_number_availables', PACKAGE = 'bmms', splitmask_focus)
}

index_to_subscript <- function(index, m) {
    .Call('_bmms_index_to_subscript', PACKAGE = 'bmms', index, m)
}

soi <- function(y, X, splits, mask_forbid, lambda_centers, lambda_ridge, mcmc, burn, radius = 2L, start_movinglev = 0L, partnum = 0L, save = TRUE, save_splitmask = FALSE) {
    .Call('_bmms_soi', PACKAGE = 'bmms', y, X, splits, mask_forbid, lambda_centers, lambda_ridge, mcmc, burn, radius, start_movinglev, partnum, save, save_splitmask)
}

#' Scalar-on-image Binary regression
#' 
#' This function applies a Bayesian Modular & Multiscale regression model to
#' a binary response, using image predictors.
#' @param y A numeric vector of length n with (0,1) entries
#' @param X An array of dimension (p1, p2, n)
#' @param centers A list with K elements, each of which is a 2-column matrix. 
#'   Element j of this list will be a matrix listing the (additional) centers to be used 
#'   to split the image space into regions. This parameter only corresponds to the starting value
#'   for MCMC. Only K will remain 
#' @param mask_forbid A matrix of dimension (p1, p2). Element (i,j) can be set to 0 if the corresponding location 
#'   cannot be used as center, 1 if it can. Typically this should be a matrix of ones.
#' @param lambda_centers A scalar parameter controlling the prior probability on the number of centers
#' @param lambda_ridge A scalar parameter corresponding to a ridge parameter for each linear regression module
#' @param mcmc Number of Markov chain-Monte Carlo iterations
#' @param burn Number of MCMC iterations to discard
#' @param radius A scalar parameter controlling the dimension of the jumps for the ``move" proposals 
#'   of the centers in MCMC
#' @param max_stages A scalar controlling the maximum number of stages. Currently fixed at K
#' @param start_movinglev A scalar smaller or equal to K indicating which 
#' @param partnum
#' @param save
#' @param save_splitmask
#' @param fixsigma
soi_binary <- function(y, X, centers, mask_forbid, lambda_centers, lambda_ridge, mcmc, burn, radius = 2L, start_movinglev = 0L, partnum = 0L, save = TRUE, save_splitmask = TRUE, fixsigma = FALSE) {
    .Call('_bmms_soi_binary', PACKAGE = 'bmms', y, X, centers, mask_forbid, lambda_centers, lambda_ridge, mcmc, burn, radius, start_movinglev, partnum, save, save_splitmask, fixsigma)
}

bvs <- function(y, X, prior, mcmc, g = -1.0, model_prior_par = 1.0, fixs = FALSE) {
    .Call('_bmms_bvs', PACKAGE = 'bmms', y, X, prior, mcmc, g, model_prior_par, fixs)
}

momscaleBVS <- function(y, Xall, starting, MCMC, gg, ss, binary = FALSE) {
    .Call('_bmms_momscaleBVS', PACKAGE = 'bmms', y, Xall, starting, MCMC, gg, ss, binary)
}

sofk <- function(y, X, start_splits, mcmc = 100L, burn = 50L, lambda = 5.0, ii = 0L, ll = 0L, silent = TRUE) {
    .Call('_bmms_sofk', PACKAGE = 'bmms', y, X, start_splits, mcmc, burn, lambda, ii, ll, silent)
}

sofk_binary <- function(y, X, start_splits, mcmc = 100L, burn = 50L, lambda = 5.0, ii = 0L, ll = 0L, silent = TRUE) {
    .Call('_bmms_sofk_binary', PACKAGE = 'bmms', y, X, start_splits, mcmc, burn, lambda, ii, ll, silent)
}

bmms_base <- function(y, X, g, mcmc, burn, splits, silent = TRUE) {
    .Call('_bmms_bmms_base', PACKAGE = 'bmms', y, X, g, mcmc, burn, splits, silent)
}

mvtruncnormal <- function(mean, l_in, u_in, Sig, n) {
    .Call('_bmms_mvtruncnormal', PACKAGE = 'bmms', mean, l_in, u_in, Sig, n)
}

mvtruncnormal_eye1 <- function(mean, l_in, u_in) {
    .Call('_bmms_mvtruncnormal_eye1', PACKAGE = 'bmms', mean, l_in, u_in)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_bmms_RcppExport_registerCCallable', PACKAGE = 'bmms')
})
